name: draggable_trash
description: Just move the items you want to delete onto the trash can, now they've been deleted.
homepage: https://github.com/taylanyildz/draggable_trash

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true